// ERRORS & MESSAGES
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

// DAYS
export const CLEAR_DAYS = 'CLEAR_DAYS';
export const GET_DAYS = 'GET_DAYS';
export const GET_DAYS_SUCCESS = 'GET_DAYS_SUCCESS';
export const GET_ALL_DAYS_SUCCESS = 'GET_ALL_DAYS_SUCCESS';

// ENTRIES
export const CLEAR_ENTRIES = 'CLEAR_ENTRIES';
export const GET_ENTRIES = 'GET_ENTRIES';
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS';
export const GET_ALL_ENTRIES_SUCCESS = 'GET_ALL_ENTRIES_SUCCESS';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';

// SHARES
export const CLEAR_SHARES = 'CLEAR_SHARES';
export const GET_SHARES = 'GET_SHARES';
export const GET_SHARES_SUCCESS = 'GET_SHARES_SUCCESS';
export const NEW_SHARE = 'NEW_SHARE';
export const NEW_SHARE_SUCCESS = 'NEW_SHARE_SUCCESS';
export const DELETE_SHARE = 'DELETE_SHARE';
export const DELETE_SHARE_SUCCESS = 'DELETE_SHARE_SUCCESS';

// MEALS
export const CLEAR_MEALS = 'CLEAR_MEALS';
export const GET_MEALS = 'GET_MEALS';
export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const NEW_MEAL = 'NEW_MEAL';
export const NEW_MEAL_SUCCESS = 'NEW_MEAL_SUCCESS';
export const DELETE_MEAL = 'DELETE_MEAL';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const PUT_MEALS = 'PUT_MEALS';
export const PUT_MEALS_SUCCESS = 'PUT_MEALS_SUCCESS';

// LISTS
export const NEW_LIST = 'NEW_LIST';
export const CLEAR_LISTS = 'CLEAR_LISTS';
export const GET_LISTS = 'GET_LISTS';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LIST = 'GET_LIST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_SETTINGS = 'GET_LIST_SETTINGS';
export const PUT_LIST_SETTINGS = 'PUT_LIST_SETTINGS';

// AUTH
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
